### PR TITLE
req.body.token -> req.body['h-captcha-response']

### PR DESCRIPTION
**Pull request by losnappas**
Doesn't work without this change. This is alll the data that is provided:
```
g-recaptcha-response  abcdrgegfd
h-captcha-response abcdrgegfd
```

### CODE REVIEW

**Comment by vastus** [comment]
Good catch @losnappas! Be sure to run `npm test` and fix any test cases that fail.

- [ ] fix failing tests

**Comment by uhteddy** [comment]
Is this going to be fixed soon? Or is this no longer maintained.

**Comment by losnappas** [comment]
Hi, must've missed that

Hopefully I fixed the erroring test? Didn't actually test, because I did this change online. \*shrug\*

**Comment by vastus** [comment]
Tests are still failing. Want to give it a go @uhteddy?

**Comment by uhteddy** [comment]
@vastus I'm not talking about the tests. I'm talking about the package itself. I was wondering if it's going to get a new version with the h-captcha-response body.

**Comment by vastus** [comment]
I am talking about the tests. This PR will not get merged before the tests pass. That's why I was asking if you wanted to give it a go in trying fixing them.

**Comment by SoapyFresh** [comment]
Any thoughts on why h-captcha-response isn’t found in the body?

**Comment by vastus** [comment]
Had some time to take a look at this today. This package expects request body to have a response token (from the captcha challenge) which should be named `token`. This is by design thus yielding this PR needless. We could have an option for the middleware where a configuration could be provided to control what the key is to grab the token from.

Here's an example request that works:

```
curl -XPOST 'host.domain/verify' \
    -H'content-type: application/json' \
    -d'{"token": "P0_eyJ0..."}'
```

I understand that the documentation isn't as thorough as it could be. I'll try to find time to work on it and hopefully add a better example and possibly the configuration option as well.

Thanks for using this middleware, let me know if you have any other issues.

**Pull request closed without merging**
